### ISSUE TITLE
Nothing else but warmup?

### ISSUE THREAD

**Issue by hermann-san** [oaken-source/exceer#1]
Hi , when I start up Exceer I can only see the below 2 screens. I can start the warm up, but when it ends, it returns to the first screen.  There are no exercises or anything else (besides the "about" button, which works OK).
I guess there should be more than that, right?
I've got a Samsung S4 with Slimkat (Slimrom) 4.4.4.
Cheers,
Hermann

![start](https://cloud.githubusercontent.com/assets/7679654/8300421/eda224c6-1984-11e5-95f3-6ef8d97b5b31.png) ![warmup](https://cloud.githubusercontent.com/assets/7679654/8300424/f0fee8ac-1984-11e5-90c1-a2ede0a7d972.png)

**Comment by oaken-source** [comment]
Yes, there should be more than that. =)

What should happen is that, after the timer has finished, the next exercise in the series should be displayed. Does it send you back to the main view directly, or after you press the button again? Does the text on the button change?

From this side, it looks like it's a compatibility issue with your version of Slimrom (or maybe the android version). I am trying to reproduce it, but did not manage to do so yet.

**Comment by oaken-source** [comment]
Okay, I just noticed that there are several things broken on android versions greater than 2.3.

I am working on fixing this asap, but it will probably be a new release and not a patch for 0.2, so it will probably not happen before next week.

**Comment by hermann-san** [comment]
when the warm-up finishes, there is a "finished" button which I can press and it will bring me back to the main view.
Thanks for looking into it.

**Comment by oaken-source** [comment]
do you remember if the app crashed on first launch?

I have the suspicion that the first launch is not properly synchronized, and the database upgrade may crash before it completes loading the defaults.

**Comment by hermann-san** [comment]
Yes, there was a app crash on the first start.

**Comment by oaken-source** [comment]
okay, this issue is fixed in the next build. I have put together a new version (0.2.1) on f-droid which should become available in the next days.

When it becomes available, you should clear Exceer's data from your device so that the databases are recreated properly. =)

**Comment by oaken-source** [comment]
v0.2.1 is available on F-Droid now. (https://f-droid.org/repository/browse/?fdfilter=exceer&fdid=org.grapentin.apps.exceer)

**Comment by hermann-san** [comment]
Thanks for the update, but I still have problems with Exceer.
I uninstalled v. 0.2 and tried to install 0.2.1 but as soon as I open Exceer on  F-Droid (0.92) , then F-Droid is crashing. I uninstalled F-Droid, re-installed it, but the problem remains. Other apps in F-Droid open with no problems, but there are a few other apps in F-Droid that also won't open (e.g. Calc , aCal and a couple of others). That seems to be a problem with F-Droid. But I'm unable to fix that. Very weirred.
I tried a fresh install on another device (LG P990 with CM11 , 4.4) , but here its the same problem. As soon as I open Exceer on  F-Droid (0.92) , then F-Droid is crashing.
I guess you can't do anything about that. In the past I didn't had such massive problems with F-Droid.

ok, I have also a tablet (Samsung tabpro with CM 11). There I can install Exceer via F-Droid , but somehow I have some doubt that Exceer is working as it should. Warm-up works ok and it goes on to the workouts. But there is no possiblity to configure anything. There is no menu with settings and there are no images or anything. Is this the expected behaivior?
In addition to the above screenshot I now get the following. BTW. do you have some screenshots on the internet on how Exceer actually should look like when it's working good?  Thanks.

![excersice1](https://cloud.githubusercontent.com/assets/7679654/8402704/f78b3794-1e3d-11e5-84a7-c4eabd0ea2c8.png)

**Comment by oaken-source** [comment]
wow, the app sure looks weird on a tablet. I should do some more UI testing there...

For the 0.3 release, there are going to be major improvements in regards to settings and exercise description, but all that 0.2.1 offers at the moment are progressions starting from zero. that is, it will track your progress but does not allow you to set a custom starting point. (will be fixed in 0.3)
0.2.1 does have images for the exercises, if you tap the exercise name at the top, but there are no descriptions or instructions, which is something that will be also fixed in 0.3.

I'm slowly working my way through these issues, but there is only so much a single man can do =)

For the exceer / f-droid crashes - have you tried to clear the apps data from the manage apps interface prior to uninstalling and then reinstalling? that may solve your issues.

**Comment by hermann-san** [comment]
tapping on the excercise name doesn't do anything on the tablet.

I thought that uninstalling the app will also clear the data. So I've not done that and I can't do it anymore because F-Droid won't let me installing Exceer. 
I guess I just leave it for now as it is and wait  for a new version of F-Droid. Maybe it will fix the problems I currently have. 
The app from  Mark Lauren  which I currently use for bodyweight exercising isn't that bad either.  I was just curious how your app looks like...

**Comment by oaken-source** [comment]
Don't forget that mine is in very early alpha ;)
